### ISSUE TITLE
BUTTON_WIDTH_PX is undefined

### ISSUE THREAD

**Issue by Strohgelaender** [Julusian/node-elgato-stream-deck#103]
I tried updating to version 7.0.1 and changed the use of `streamDeck.ICON_SIZE` to the new properties `BUTTON_WIDTH_PX` and `BUTTON_HEIGHT_PX`. After doing so I got an error that my icons are the wrong size, caused by these two properties returning undefined.

I'm using a Streamdeck XL, `getHidDeviceInfo` gives  `productId: 108,  vendorId: 4057`. I hope this is enough information for you to replicate the issue.

As a workaround, I'm using my own constant `const ICON_SIZE = 96;`. This is fine for my application since it's a personal project, but obviously not a solution if you want to support different devices.

**Comment by Julusian** [comment]
This is an intentional change, none of those properties you list exist anymore. Instead you should look at the specific control inside the `CONTROLS` property, to find its dimensions.
https://github.com/Julusian/node-elgato-stream-deck/releases/tag/v7.0.0-0

This was done to unify things for the different control types, and to be ready in case a streamdeck is released which wants to make use of this.

I appear to have not updated all the examples to this new format yet, I shall go through and do those soon

**Comment by Strohgelaender** [comment]
Thanks for the information and for the link to the release notes, I could not find them yesterday.

Could you update the [examples ](https://github.com/Julusian/node-elgato-stream-deck/tree/main/packages/node/examples) accordingly? I used `BUTTON_HEIGHT_PX` since PR #97 updated them to use `BUTTON_HEIGHT_PX`. 

Thanks for the great work with this library!
