### ISSUE TITLE
Planned support for non-elgato devices?

### ISSUE THREAD

**Issue by Billiam** [Julusian/node-elgato-stream-deck#107]
Just wondering if there are plans to support the (less expensive) mirabox "stream docks" and similar devices that I've seen pop up.

I see a proof of concept repository (https://github.com/rigor789/mirabox-streamdock-node) but I'd love to hear your thoughts on compatibility between the two device protocols.

**Comment by Julusian** [comment]
I'm currently not too keen on supporting all of these. I did have a play with the ajazz one, which didn't emit both key down and up events which made it problematic for my use case, so it didn't go anywhere.

Based on that repository, it looks to be using raw usb rather than hid which means the internal implementation of everything would likely be different compared to a streamdeck. Which starts to feel like it could justify being a separate library (which I guess could be part of this repository)

And based on that sample size of 2, it suggests that supporting these clones would be a long battle of constantly adding new models, each with a slightly or very different protocol, or even transport.  
Keeping on top of just the elgato models can be a challenge at times, with new revisions released at random with slight protocol changes

**Comment by Billiam** [comment]
Thanks very much!
