### ISSUE TITLE
Raspberry Pi WebHID

### ISSUE THREAD

**Issue by nerdworldDE** [Julusian/node-elgato-stream-deck#58]
Anyone figured out how to setup the StreamDeck on Raspbian?

All i get is this - even tho udev rules are setup.
```No device access granted: NotAllowedError: Failed to open the device.```

The device runs flawlessly with the normal node code.

**Comment by Julusian** [comment]
does it work with webhid on other machines?

**Comment by nerdworldDE** [comment]
Yes. 

Am 19. Okt. 2022, 10:58, um 10:58, Julian Waller ***@***.***> schrieb:
>does it work with webhid on other machines?
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Julusian/node-elgato-stream-deck/issues/58#issuecomment-1283658121
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by Julusian** [comment]
Im afraid I don't have any good suggestions for you.
I use linux as my main os, and haven't had any issues recently with webhid since setting up udev rules (which were also needed for node).

The one quirk I did have a while back was not being able to use the original revision of the 15 key on linux (with the hidraw backend, which is now the default for this library). But that got fixed by some kernel update a year or so ago. Perhaps this is what you are seeing?
