### ISSUE TITLE
Error: Failed to find binding for HID_hidraw

### ISSUE THREAD

**Issue by ibito** [Julusian/node-elgato-stream-deck#90]
When using `npm start` it works flawlessly, however, when I build the app, I get 
` Error: Failed to find binding for HID_hidraw`

It's worth saying I'm using node 20 and electron 26

**Comment by Julusian** [comment]
This is likely happening because your electron build process is not making sure that the node-hid prebuilds are copied into the binary. I think this should be done for you automatically, but maybe it isn't always.

There isn't anything to do in this library for this, https://github.com/node-hid/node-hid is a better place, but will need some more details to be able to help at all
